### ISSUE TITLE
Create stable release

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-talk-recording#10]
Hi, 

in order to use this repo in AIO, it would be great if there was a stable release that we can use to pin the version. 

This is needed for https://github.com/nextcloud/all-in-one/issues/3570

Thanks for considering!

**Comment by nickvergessen** [comment]
Just a git tag is enough?

**Comment by szaimen** [comment]
> Just a git tag is enough?

Yes

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/nextcloud-talk-recording/releases/tag/v0.1

**Comment by szaimen** [comment]
Thanks! :)
