### ISSUE TITLE
Cant see the record button 

### ISSUE THREAD

**Issue by zydisney** [nextcloud/nextcloud-talk-recording#20]
I have configure the HPB signaling server, and record server. but I cannot see the record button during the call.
<img width="785" alt="Screenshot 2024-04-06 at 16 59 42" src="https://github.com/nextcloud/nextcloud-talk-recording/assets/22111213/c858a137-2021-4169-a45c-cc7491d8fdb7">
Signaling server log seems ok
```
spreedbackend-1  | room.go:665: Session 
2VwgbQQeB7ZBHmAJG_bfBFQsXTAgoYx3hGfWlnaA55N8RENUNURmVkptTi0wQ0ViTnkwcjlDaUpsTld1YUljQkhPQnZfbVhVeEV4cnY0QjhsU3dOaHRNRlYtS1g3TXFZeDZLRlBkVXpuRENlQ3JZTWE5TDFSdkZrUFdRVTNfNkxQVEJSQ0pOSGFfN1ZwcFZQUFpCWHM0Q252a1FyRy1DTjN6aVFaOFVDYmVEZ0Zza1VIUFU5UFFZZl9tRjFoeUhmbXZzZGRMaC1CfDUzMDQ5MzIxNzE= 
joined call vzh8wuuy
```
Record backend log also no error
```
2024-04-06 16:59:28 INFO:werkzeug:172.19.0.1 - - [06/Apr/2024 08:59:28] "GET /api/v1/welcome HTTP/1.1" 200 -
```
But there is no record button any way. How can I fix it?
<img width="305" alt="image" src="https://github.com/nextcloud/nextcloud-talk-recording/assets/22111213/03b170ae-b386-422d-876a-89aad0826189">

Spreed version: 19.0.0

**Comment by nickvergessen** [comment]
You didn't set a recording secret? 🤔

**Comment by zydisney** [comment]
> You didn't set a recording secret? 🤔

Yes, I'm testing it in LAN environment, so I didn't set the secret. Is it compulsory?

**Comment by nickvergessen** [comment]
Same for the HPB. Unless you configure it, the Nextcloud server can not authenticate towards the Recording or Signaling server and vice versa
